server:
  port: 8080

spring:
  kafka:
    security:
      protocol: "PLAINTEXT"
    bootstrap-servers: http://localhost:9092
  flyway:
    enabled: true
    default-schema: public
    baseline-on-migrate: true

  datasource:
#    hikari:
#      jdbc-url: jdbc:postgresql://localhost:5432/item
#      username: Vlad
#      password: 12345
    url: jdbc:postgresql://localhost:5432/item?&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: Vlad
    password: 12345
  jpa:
    generate-ddl: true
    hibernate:
      format-sql: true
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        generate_statistics: true
        order_updates: true


kafka:
  import:
    task:
      update-status: import.task.update.status
    item:
      topic: import.item
      group-id: import_item

logging:
  level:
    org.hibernate:
      engine.jdbc.batch.internal.BatchingBatch: DEBUG
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: DEBUG
    ru:
      otus: DEBUG

